# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scribe < Formula
  desc "Command line interface for translating natural language prompts into SQL queries."
  homepage "https://github.com/mergestat/scribe"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mergestat/scribe/releases/download/v0.0.1/scribe_Darwin_arm64.tar.gz"
      sha256 "ee4a381b2b7d38a7bcceafd4fb52af19703f3de61a474d5ba804cbeb728d787f"

      def install
        bin.install "scribe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mergestat/scribe/releases/download/v0.0.1/scribe_Linux_arm64.tar.gz"
      sha256 "7ef3f8208810149a5b2e29eb07debc13e488e4a2f518edcbad027dc3ef740da4"

      def install
        bin.install "scribe"
      end
    end
  end
end
